const generateHTMLReport = (data, company) => {
  return `
  <!DOCTYPE html>
  <html>

  <head>
    <style>

      body {
        font-family: Arial, sans-serif;
        background: #e5e7eb;
        padding: 40px;
        color: #111827;
      }

      .container {
        max-width: 900px;
        margin: auto;
        background: white;
        border-radius: 20px;
        overflow: hidden;
        box-shadow: 0 15px 40px rgba(0,0,0,0.12);
      }

      .header {
        background: linear-gradient(135deg, #2563eb, #1e40af);
        color: white;
        padding: 50px;
      }

      .header h1 {
        margin: 0;
        font-size: 38px;
      }

      .header p {
        margin-top: 12px;
        opacity: 0.95;
        font-size: 16px;
        color: #e0e7ff;
      }

      .content {
        padding: 40px;
      }

      .section {
        margin-bottom: 40px;
      }

      .section h2 {
        color: #1d4ed8;
        font-size: 24px;
        margin-bottom: 18px;
      }

      .card {
        background: white;
        padding: 24px;
        border-radius: 14px;
        border: 1px solid #d1d5db;
        box-shadow: 0 4px 12px rgba(0,0,0,0.04);
      }

      p {
        line-height: 1.8;
        color: #111827;
        font-size: 15px;
      }

      ul {
        padding-left: 20px;
      }

      li {
        margin-bottom: 12px;
        color: #111827;
        line-height: 1.7;
        font-size: 15px;
      }

      .footer {
        text-align: center;
        padding: 30px;
        background: #f3f4f6;
        color: #6b7280;
        font-size: 14px;
      }

      .badge {
        display: inline-block;
        background: rgba(255,255,255,0.18);
        padding: 10px 18px;
        border-radius: 999px;
        margin-top: 20px;
        font-size: 14px;
      }

    </style>
  </head>

  <body>

    <div class="container">

      <div class="header">
        <h1>${company} AI Audit Report</h1>

        <p>
          AI-powered business analysis and automation recommendations
        </p>

        <div class="badge">
          Generated by SimplifiQ AI
        </div>
      </div>

      <div class="content">

        <div class="section">
          <h2>Company Summary</h2>

          <div class="card">
            <p>${data.companySummary}</p>
          </div>
        </div>

        <div class="section">
          <h2>Pain Points</h2>

          <div class="card">
            <ul>
              ${data.painPoints.map(item => `<li>${item}</li>`).join("")}
            </ul>
          </div>
        </div>

        <div class="section">
          <h2>AI Opportunities</h2>

          <div class="card">
            <ul>
              ${data.aiOpportunities.map(item => `<li>${item}</li>`).join("")}
            </ul>
          </div>
        </div>

        <div class="section">
          <h2>Recommendations</h2>

          <div class="card">
            <ul>
              ${data.recommendations.map(item => `<li>${item}</li>`).join("")}
            </ul>
          </div>
        </div>

      </div>

      <div class="footer">
        Generated automatically by SimplifiQ AI Lead Automation System
      </div>

    </div>

  </body>
  </html>
  `;
};

module.exports = generateHTMLReport;