const axios = require("axios");
const fs = require("fs");
const path = require("path");
const { cleanupPDF } = require("./pdfService");

const sendEmail = async (to, company, pdfPath) => {
  // Read the PDF and convert to base64
  const pdfBuffer = fs.readFileSync(pdfPath);
  const pdfBase64 = pdfBuffer.toString("base64");
  const filename = `${company}-Audit.pdf`;

  const payload = {
    sender: {
      name: "SimplifiQ AI",
      email: process.env.BREVO_USER,
    },
    to: [{ email: to }],
    subject: `${company} — AI Business Audit Report`,
    htmlContent: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 32px; background: #f9fafb; border-radius: 12px;">
        <h2 style="color: #1d4ed8; margin-bottom: 12px;">Your AI Audit Report is Ready</h2>
        <p style="color: #374151; line-height: 1.7;">
          Hello,<br><br>
          Please find attached the AI-generated business audit report for <strong>${company}</strong>.
          The report includes a company summary, identified pain points, AI opportunities, and strategic recommendations.
        </p>
        <p style="color: #6b7280; font-size: 13px; margin-top: 24px;">
          Generated by SimplifiQ AI Lead System. If you don't see this in your inbox, please check your spam or junk folder.
        </p>
      </div>
    `,
    attachment: [
      {
        content: pdfBase64,
        name: filename,
      },
    ],
  };

  const response = await axios.post(
    "https://api.brevo.com/v3/smtp/email",
    payload,
    {
      headers: {
        "api-key": process.env.BREVO_API_KEY,
        "Content-Type": "application/json",
      },
    }
  );

  console.log("Email sent to", to, "| messageId:", response.data.messageId);
  cleanupPDF(pdfPath);
};

module.exports = sendEmail;