const nodemailer = require("nodemailer");
const { cleanupPDF } = require("./pdfService");

const sendEmail = async (to, company, pdfPath) => {
  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });

  const info = await transporter.sendMail({
    from: process.env.EMAIL_USER,
    to,
    subject: `${company} — AI Business Audit Report`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 32px; background: #f9fafb; border-radius: 12px;">
        <h2 style="color: #1d4ed8; margin-bottom: 12px;">Your AI Audit Report is Ready</h2>
        <p style="color: #374151; line-height: 1.7;">
          Hello,<br><br>
          Please find attached the AI-generated business audit report for <strong>${company}</strong>.
          The report includes a company summary, identified pain points, AI opportunities, and strategic recommendations.
        </p>
        <p style="color: #6b7280; font-size: 13px; margin-top: 24px;">
          Generated by SimplifiQ AI Lead System. If you don't see this in your inbox, please check your spam or junk folder.
        </p>
      </div>
    `,
    attachments: [
      {
        filename: `${company}-Audit.pdf`,
        path: pdfPath,
      },
    ],
  });

  console.log("Email sent to", to, "| messageId:", info.messageId);

  // Delete the PDF from disk now that it's been sent
  cleanupPDF(pdfPath);
};

module.exports = sendEmail;
